#+TITLE: Doom emacs config
#+AUTHOR: atwist227
#+STARTUP: show3levels

本文档是我的 Doom Emacs 配置文件。
在 Doom Emacs 中开启模组 literature 即可在每次保存文件或运行 doom sync 命令时自动生成 config.el.
* 基础设置 (General Settings)
** 文件头
lexical-binding
#+begin_src elisp
;;; config.el -*- lexical-binding: t; -*-
#+end_src

package.el
#+begin_src elisp :tangle packages.el
;; -*- no-byte-compile: t; -*-
#+end_src

** 基本设置
#+begin_src elisp
(show-paren-mode t)

(setq auto-save-default t
      make-backup-files t)

(setq confirm-kill-emacs nil)
(setq display-line-numbers-type t)

;; 菜单栏(用得不熟，开着菜单适应适应)
(menu-bar-mode 1)
#+end_src

** 外观 (Appearance)
*** 主题
设置 Doom Emacs 的主题。
#+BEGIN_SRC elisp
;; (setq doom-theme 'doom-one)
(setq doom-theme 'doom-vibrant)
#+END_SRC

*** 窗口大小
#+begin_src elisp :tangle no
(add-to-list 'initial-frame-alist '(width . 80))
(add-to-list 'initial-frame-alist '(height . 36))
#+end_src

*** 字体
#+BEGIN_SRC elisp
(when (eq system-type 'windows-nt)
  (setq doom-font (font-spec :family "SauceCodePro NF" :size 13.0))
  (set-fontset-font "fontset-default" 'han (font-spec :family "Noto Sans SC" :size 14.0)))

(when (eq system-type 'gnu/linux)
  (setq doom-font (font-spec :family "JetBrainsMono NF" :size 13.0))
  (set-fontset-font "fontset-default" 'han (font-spec :family "Noto Sans CJK SC" :size 14.0)))
#+end_src

* Doom 模块配置 (Doom Module Configuration)
** :editor
*** evil
#+BEGIN_SRC elisp
(after! evil
  (setq evil-move-cursor-back nil     ; don't move the block cursor when toggling insert mode
        evil-kill-on-visual-paste nil ; don't put overwritten text in the kill ring
        evil-want-fine-undo t
        evil-move-beyond-eol t
        ;; evil-want-minibuffer t
        +evil-want-o/O-to-continue-comments nil))
#+END_SRC

*** snippets
#+begin_src elisp :tangle no
(setq yas-snippet-dirs '((concat doom-user-dir "snippets/")
                         (concat doom-emacs-dir ".local/etc/yasnippet/snippets/")))
#+end_src

** :lang
*** latex
**** pdf 预览
#+BEGIN_SRC elisp
(after! tex
  (when (eq system-type 'gnu/linux)
    (setq TeX-view-program-selection '((output-pdf "PDF Tools")))
    (add-hook 'TeX-after-compilation-finished-functions #'TeX-revert-document-buffer)
    ;; 适应页面宽度
    (add-hook 'pdf-view-mode-hook 'pdf-view-fit-width-to-window))
  (when (eq system-type 'windows-nt)
    (setq TeX-view-program-list
          '(("Sumatra PDF" ("\"%LOCALAPPDATA%/SumatraPDF/SumatraPDF.exe\" -reuse-instance" (mode-io-correlate " -forward-search %b %n ") " %o"))))
    (add-to-list 'TeX-view-program-selection '(output-pdf "Sumatra PDF"))))
#+end_src

pdf-tools 需要 =epdfinfo server= 支持，在 linux 环境下只需要在 emacs 中执行命令 ~M-x pdf-tools-install~ 即可安装。

Sumatra PDF *反向跳转* 需要在 Sumatra PDF “设置” > “选项” > “设置反向搜索命令行” 中配置
#+begin_src bash :tangle no
"C:\msys64\mingw64\bin\emacsclientw.exe" -n +%l "%f"
#+end_src

**** cdlatex
#+BEGIN_SRC elisp
(after! cdlatex
  (map! :map cdlatex-mode-map
        :i "TAB" #'cdlatex-tab)

  (setq cdlatex-math-modify-alist
        '((?b "\\mathbb" nil t nil nil)
          (?k "\\mathfrak" nil t nil nil)
          (?m "\\mathrr" nil t nil nil)
          (?o "\\operatorname" nil t nil nil)
          )
        cdlatex-math-symbol-alist
        '((?e ("\\varepsilon" "\\epsilon"))
          (?f ("\\varphi" "\\phi"))
          (?0 ("\\varnothing" "\\emptyset"))
          )
       ;; cdlatex-command-alist ;; expand with <TAB>
       ;; '(("eqn" "Insert an EQUATION* environment template" "" cdlatex-environment ("equation*") t nil)
       ;;   ("aln" "Insert an ALIGN* environment template" "" cdlatex-environment ("align*") t nil)
       ;;   ("op" "Insert \\operatorname{}()" "\\operatorname{?}()" cdlatex-position-cursor nil nil t)
       ;;  )
  ))
#+END_SRC

*** org
:PROPERTIES:
:header-args:elisp: :tangle no
:END:
**** +roam2
***** Directories
#+begin_src elisp
(after! org-roam
  :init
  (setq org-roam-directory "~/Seafile/Projects/org/pages")
  (setq org-roam-dailies-directory "../journals")
  :custom
  (setq org-id-link-to-org-use-id 'create-if-interactive)
  )
#+end_src
***** org-roam-ui
#+begin_src elisp
(use-package! websocket
    :after org-roam)

(use-package! org-roam-ui
    :after org-roam ;; or :after org
;;         normally we'd recommend hooking orui after org-roam, but since org-roam does not have
;;         a hookable mode anymore, you're advised to pick something yourself
;;         if you don't care about startup time, use
;;  :hook (after-init . org-roam-ui-mode)
    :config
    (setq org-roam-ui-sync-theme t
          org-roam-ui-follow t
          org-roam-ui-update-on-save t
          org-roam-ui-open-on-start t))
#+end_src
**** 关闭上下标预览
#+begin_src elisp
(setq org-pretty-entities-include-sub-superscripts nil)
#+end_src
* 其他包 (other packages)
** [[https://github.com/laishulu/emacs-smart-input-source/tree/master][smart-input-source]]
#+begin_src elisp :tangle packages.el
(package! sis)
#+end_src

注意！ windows 11 系统下要开启输入法兼容性模式
#+begin_src elisp
(use-package! sis
  :init
  (if (eq system-type 'gnu/linux)
      (sis-ism-lazyman-config "1" "2" 'fcitx5))
  :config
  ;; 启用 /光标颜色/ 模式
  (sis-global-cursor-color-mode t)
  ;; 启用 /respect/ 模式
  (sis-global-respect-mode t)
  ;; 为所有缓冲区启用 /context/ 模式
  (sis-global-context-mode t)
  ;; 为所有缓冲区启用 /inline english/ 模式
  (sis-global-inline-mode t))
#+end_src

* 其他 (Miscellaneous)
** windows
*** 指定临时文件夹
windows 系统访问权限的原因 emacs 不一定能访问 temp 文件夹，这会导致 org-latex-preview 无法工作，故重新指定临时文件夹。参考[[https://emacs-china.org/t/emacs/21689][emacs 笔记问题（数学、物理），希望大家不吝赐教 （预览以及插入问题）。]]
#+begin_src elisp
(when (eq system-type 'windows-nt)
  (setq temporary-file-directory "~/AppData/LocalLow/Temp/"))
#+end_src

** wsl(已经弃用)
:PROPERTIES:
:header-args:elisp: :tangle no
:END:
*** 修复 Wayland 环境下的 PGTK 算术溢出错误
也是 org-latex-preview 使用中发现的问题，参考[[https://emacs-china.org/t/wslg-x-display-mm-height-0/22547/1][WSLg下 (x-display-mm-height)返回0（异常）]]
#+BEGIN_SRC elisp
(setq display-mm-dimensions-alist '(("wayland-0" . (366 . 260))))
#+END_SRC

