#+TITLE: Doom emacs config
#+AUTHOR: atwist227
#+PROPERTY: header-args:emacs-lisp :tangle config.el
#+STARTUP: show2levels

本文档是我的 Doom Emacs 配置文件。
使用命令 ~M-x org-babel-tangle~ 生成配置文件。

* 基础设置 (General Settings)
** 启用词法绑定
与动态绑定 (Dynamic Binding) 不同，不受调用栈影响。
#+begin_src emacs-lisp
;;; config.el -*- lexical-binding: t; -*-
#+end_src

** 编辑行为 (Editing Behavior)
*** 开启自动保存和备份
#+BEGIN_SRC emacs-lisp
(setq auto-save-default t
      make-backup-files t)
#+END_SRC

*** 关闭退出 Emacs 时的确认提示
#+BEGIN_SRC emacs-lisp
(setq confirm-kill-emacs nil)
#+END_SRC

** 外观 (Appearance)
*** 主题
设置 Doom Emacs 的主题。
#+BEGIN_SRC emacs-lisp
(setq doom-theme 'doom-one)
#+END_SRC
*** 窗口大小
#+begin_src emacs-lisp
(add-to-list 'initial-frame-alist '(width . 80))
(add-to-list 'initial-frame-alist '(height . 36))
#+end_src
*** 字体
**** 安装 Nerd 字体
Linux 下 =JetBrains Mono= 字体下载脚本
#+begin_src bash
mkdir -p ~/.local/share/fonts
wget -O ~/.local/share/fonts/JetBrainsMono.zip https://download.jetbrains.com/fonts/JetBrainsMono.zip
unzip ~/.local/share/fonts/JetBrainsMono.zip -d ~/.local/share/fonts
rm ~/.local/share/fonts/JetBrainsMono.zip
fc-cache -fv
#+end_src
**** Windows 系统字体配置
#+BEGIN_SRC emacs-lisp :tangle (if (eq system-type 'windows-nt) "yes" "no")
(setq doom-font (font-spec :family "SauceCodePro NF" :size 13.0))
(set-fontset-font "fontset-default" 'han (font-spec :family "Noto Sans SC" :size 14.0))
#+END_SRC
**** Linux 系统字体配置
#+begin_src emacs-lisp :tangle (if (eq system-type 'gnu/linux) "yes" "no")
(setq doom-font (font-spec :family "JetBrainsMono NF" :size 13.0))
(set-fontset-font "fontset-default" 'han (font-spec :family "Noto Sans CJK SC" :size 14.0))
#+end_src
*** 开启行号显示
#+BEGIN_SRC emacs-lisp
(setq display-line-numbers-type t)
#+END_SRC
* Doom 模块配置 (Doom Module Configuration)
** :editor
*** evil
#+BEGIN_SRC emacs-lisp
(after! evil
  (setq evil-move-cursor-back nil     ; don't move the block cursor when toggling insert mode
        evil-kill-on-visual-paste nil ; don't put overwritten text in the kill ring
        evil-want-fine-undo t
        evil-move-beyond-eol t
        ;; evil-want-minibuffer t
        +evil-want-o/O-to-continue-comments nil))
#+END_SRC
** :lang
*** latex
**** pdf 预览
***** TODO pdf-tools
不喜欢 pdf-tools 非平滑滚动，以后更换
pdf-tools 需要 =epdfinfo server= 支持，在 linux 环境下只需要在 emacs 中执行命令 ~M-x pdf-tools-install~ 即可安装。
关于 pdf-tools 的配置。
#+BEGIN_SRC emacs-lisp :header-args:emacs-lisp: :tangle (if (eq system-type 'gnu/linux) "yes" "no")
(after! tex
  (setq TeX-view-program-selection '((output-pdf "PDF Tools")))
  (add-hook 'TeX-after-compilation-finished-functions #'TeX-revert-document-buffer))
#+END_SRC
***** Sumatra PDF (windows)
*正向跳转配置*
#+begin_src emacs-lisp
(after! tex
  (setq TeX-view-program-list
        '(("Sumatra PDF" ("\"%LOCALAPPDATA%/SumatraPDF/SumatraPDF.exe\" -reuse-instance" (mode-io-correlate " -forward-search %b %n ") " %o"))))
  (add-to-list 'TeX-view-program-selection '(output-pdf "Sumatra PDF")))
#+end_src
*反向跳转* 需要在 Sumatra PDF “设置” > “选项” > “设置反向搜索命令行” 中配置
#+begin_src bash
"C:\msys64\mingw64\bin\emacsclientw.exe" -n +%l "%f"
#+end_src
**** 输入 ^ _ 后自动插入花括号
#+begin_src emacs-lisp
(after! tex
  (setq TeX-electric-sub-and-superscript t))
#+end_src
**** cdlatex
#+BEGIN_SRC emacs-lisp
(after! cdlatex
  (map! :map cdlatex-mode-map
        :i "TAB" #'cdlatex-tab)

  (setq cdlatex-math-modify-alist
        '((?b "\\mathbb" nil t nil nil)
          (?k "\\mathfrak" nil t nil nil)
          (?m "\\mathrr" nil t nil nil)
          (?o "\\operatorname" nil t nil nil)
          )
        cdlatex-math-symbol-alist
        '((?e ("\\varepsilon" "\\epsilon"))
          (?f ("\\varphi" "\\phi"))
          (?0 ("\\varnothing" "\\emptyset"))
          )
       ;; cdlatex-command-alist ;; expand with <TAB>
       ;; '(("eqn" "Insert an EQUATION* environment template" "" cdlatex-environment ("equation*") t nil)
       ;;   ("aln" "Insert an ALIGN* environment template" "" cdlatex-environment ("align*") t nil)
       ;;   ("op" "Insert \\operatorname{}()" "\\operatorname{?}()" cdlatex-position-cursor nil nil t)
       ;;  )
  ))
#+END_SRC
*** org
**** +roam2
***** Directories
#+begin_src emacs-lisp :tangle (if (eq system-type 'windows-nt) "yes" "no")
(after! org-roam
  :init
  (setq org-roam-directory "~/Seafile/Projects/org/pages")
  (setq org-roam-dailies-directory "../journals")
  :custom
  (setq org-id-link-to-org-use-id 'create-if-interactive)
  )
#+end_src
***** org-roam-ui
#+begin_src emacs-lisp
(use-package! websocket
    :after org-roam)

(use-package! org-roam-ui
    :after org-roam ;; or :after org
;;         normally we'd recommend hooking orui after org-roam, but since org-roam does not have
;;         a hookable mode anymore, you're advised to pick something yourself
;;         if you don't care about startup time, use
;;  :hook (after-init . org-roam-ui-mode)
    :config
    (setq org-roam-ui-sync-theme t
          org-roam-ui-follow t
          org-roam-ui-update-on-save t
          org-roam-ui-open-on-start t))
#+end_src
**** 关闭上下标预览
#+begin_src emacs-lisp
(setq org-pretty-entities-include-sub-superscripts nil)
#+end_src
* 其他包 (other packages)
** [[https://github.com/DogLooksGood/emacs-rime][emacs-rime]] (弃用, 改用 sis 更统一和方便设置)
:PROPERTIES:
:header-args:emacs-lisp: :tangle no
:END:
仅在 linux 系统下使用（为了匹配 wsl 选择了 emacs 内置输入法）。
*** 设置默认输入法为 rime
#+begin_src emacs-lisp
(setq default-input-method "rime")
#+end_src
*** 基本设置
#+begin_src emacs-lisp
(after! rime
  (setq rime-show-candidate 'posframe)
  (setq rime-user-data-dir "~/.local/share/rime/rime-data/") ; FIXME 根据主机配置调整
  (setq rime-disable-predicates
        '(rime-predicate-evil-mode-p
          rime-predicate-org-latex-mode-p
          rime-predicate-tex-math-or-command-p
          rime-predicate-in-code-string-p
          rime-predicate-after-alphabet-char-p
          rime-predicate-space-after-cc-p
          rime-predicate-punctuation-line-begin-p
          rime-predicate-punctuation-after-ascii-p))
  (setq mode-line-mule-info '((:eval (rime-lighter))))); 临时启用英文提示
#+end_src
** [[https://github.com/laishulu/emacs-smart-input-source/tree/master][smart-input-source]]
:PROPERTIES:
:header-args:emacs-lisp: :tangle yes
:END:
注意！ windows 11 系统下要开启输入法兼容性模式
#+begin_src emacs-lisp
(use-package! sis
  :init
  (if (eq system-type 'gnu/linux)
      (sis-ism-lazyman-config "1" "2" 'fcitx5))
  :config
  ;; 启用 /光标颜色/ 模式
  (sis-global-cursor-color-mode t)
  ;; 启用 /respect/ 模式
  (sis-global-respect-mode t)
  ;; 为所有缓冲区启用 /context/ 模式
  (sis-global-context-mode t)
  ;; 为所有缓冲区启用 /inline english/ 模式
  (sis-global-inline-mode t))
#+end_src
* 其他 (Miscellaneous)
** windows
:PROPERTIES:
:header-args:emacs-lisp: :tangle (if (eq system-type 'windows-nt) "yes" "no")
:END:
*** 指定临时文件夹
windows 系统访问权限的原因 emacs 不一定能访问 temp 文件夹，这会导致 org-latex-preview 无法工作，故重新指定临时文件夹。参考[[https://emacs-china.org/t/emacs/21689][emacs 笔记问题（数学、物理），希望大家不吝赐教 （预览以及插入问题）。]]
#+begin_src emacs-lisp
(setq temporary-file-directory "~/.opt/emacs_temp")
#+end_src
** wsl(已经弃用)
:PROPERTIES:
:header-args:emacs-lisp: :tangle no
:END:
*** 修复 Wayland 环境下的 PGTK 算术溢出错误
也是 org-latex-preview 使用中发现的问题，参考[[https://emacs-china.org/t/wslg-x-display-mm-height-0/22547/1][WSLg下 (x-display-mm-height)返回0（异常）]]
#+BEGIN_SRC emacs-lisp
(setq display-mm-dimensions-alist '(("wayland-0" . (366 . 260))))
#+END_SRC
** 快捷键设置
*** <SPC><TAB>切换输入法,<SPC><\>依旧可以使用(弃用)
#+BEGIN_SRC emacs-lisp :tangle no
(map! :leader
      :desc "Toggle input method"
      "TAB" #'toggle-input-method)
#+END_SRC
